speedMultiplier = 1 #SPECIFIES HOW MANY TIMES THE PHYSICS LOOP RUNS
windowWidth = 1000
windowHeight = 750
displayingDetail = False
selectedItem = None
selectedBeeArray = []
flowerPlacing = False
createdFlowerRate = 1.0
createdFlowerColour = (100,100,100)